artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/Srinidhisankar20/Dataset/raw/refs/heads/main/Potato_leaf_disease.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  